### ISSUE TITLE
Vertical Slice Checklist

### ISSUE THREAD

**Issue by JordanEllis6809** [colonyportal/colonyPortal#15]
- [x] Example Colony
- [x] Login To Colony
- [ ] (MVP) See Basics of the Colony [domains, users + rep?, tasks, something]
- [ ] (MVP) See Basics of a Domain [task list]
- [x] GitHub Auth W/ Domain's Repo
- [x] Select 'Import Issues From GitHub'
- [ ] (MVP) See / Filter Issues From GitHub [select repo at least]
- [x] Select A Issue To Convert To Colony Task
- [x] Generate Tasks From Issues
  * Documented here https://github.com/colonyportal/GithubColony/issues/12 
- [x] Modify Task & Add It
- [ ] IPFS Content
- [ ] The rest of the task life cycle in colony....
  * Documented here https://github.com/colonyportal/GithubColony/issues/12

**Comment by JordanEllis6809** [comment]
All of the remaining items here have been broken up into their own tasks. Closing.
